Added 'I love git' ascii art for git lov typo
Xaxetrov/git-typo pull request #25
Opened 2019-10-29 18:01 UTC by avanzzzi

Closes #19

2019-10-29 18:12 UTC, Xaxetrov commented
Thanks for your contribution ! I can have a look at it on sunday

2019-11-04 12:33 UTC, Xaxetrov requested changes

2019-11-04 12:33 UTC, Xaxetrov commented on shellGitTypo.sh
> +'
I don't really get the heart. Where is it ?

2019-11-04 12:33 UTC, Xaxetrov commented on shellGitTypo.sh
> +    clear; echo "$gitTypoHeart"
Please do not clear the shell if the ascii art is not dynamic. Instead just display the image like it is done for "git statue"

2019-11-04 12:33 UTC, Xaxetrov commented on shellGitTypo.sh
> +  # log
Please keep the easter eggs ordered alphabetically.

2019-11-04 12:33 UTC, Xaxetrov commented on shellGitTypo.sh
> +gitTypoHeart='
please keep ascii art constants ordered alphabetically.

2019-11-05 17:56 UTC, avanzzzi commented on shellGitTypo.sh
> +'
Changed to something that looks like a heart now.

2019-11-06 19:51 UTC, Xaxetrov approved these changes

2019-11-06 19:51 UTC, Xaxetrov commented on shellGitTypo.sh
> +gitTypoHeart='
Haha nice so big.

2019-11-06 19:51 UTC, Xaxetrov commented on shellGitTypo.sh
> +    sleep 1.5
Not sure about the sleep but we will keep it and I'll see later if I remove it or add it on other ascii arts.

2019-11-06 19:52 UTC, merged